name: Formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - run: |
          wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s 21
          sudo apt-get install -y clang-format-21
      - run: clang-format-21 --version
      - name: Check formatting
        run: |
          files=$(find . \
            \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' \
               -o -name '*.h' -o -name '*.hh' -o -name '*.hpp' \) \
            -not -path './.git/*')

          if [ -n "$files" ]; then
            clang-format-21 --dry-run --Werror $files
          else
            echo "No C/C++ files found."
          fi
